### ISSUE TITLE
Build fail, ada-util ADS not found

### ISSUE THREAD

**Issue by bencz** [stcarrez/ada-ado#2]
Hi!

I am having the following problem to compile:

> root@debian:/home/syner/Ada/ada-ado# ./configure
> checking build system type... powerpc64-unknown-linux-gnu
> checking host system type... powerpc64-unknown-linux-gnu
> checking target system type... powerpc64-unknown-linux-gnu
> checking for pandoc... no
> checking for dynamo... no
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables...
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking MySQL configuration... mysql_config
> checking for library containing mysql_init... no
> checking for sqlite3_open in -lsqlite3... yes
> checking for sqlite3... yes
> checking for PQexec in -lpq... yes
> checking for psql... yes
> checking for a BSD-compatible install... /usr/bin/install -c
> checking for gprbuild... gprbuild
> checking for gprclean... gprclean
> checking whether make sets $(MAKE)... yes
> checking whether ln -s works... yes
> checking shared library support... no
> checking distribution build... yes
> checking coverage support... no
> checking number of processors... 8
> checking for gprinstall... gprinstall
> checking whether util_config project exists... no
> checking for util_config.gpr installation...
> checking for gprinstall... (cached) gprinstall
> checking installation of Ada source files... <prefix>/include
> checking installation of Ada ALI files... <prefix>/lib
> checking installation of library files... <prefix>/lib
> checking installation of GNAT project files... <prefix>/lib/gnat
> checking preparing for GNAT project ado... done
> checking Ada Utility Library... trying util
> checking whether util project exists in gnatmake's search path... no
> checking for Ada Utility Library project in ../ada-util... yes
> checking for additional linker options for libada_ado_mysql... none
> checking for additional linker options for libada_ado_sqlite... none
> checking for additional linker options for libada_ado_postgresql... none
> configure: creating ./config.status
> config.status: creating Makefile
> config.status: creating ado.gpr
> config.status: creating ado_tests.gpr
> config.status: creating samples.gpr
> config.status: creating distrib/ado.gpr
> config.status: creating distrib/ado_mysql.gpr
> config.status: creating ado_mysql.gpr
> config.status: creating ado_sqlite.gpr
> config.status: creating ado_postgresql.gpr
> configure: supported databases:  sqlite postgresql

--------------------------------

> root@debian:/home/syner/Ada/ada-ado# make
> make ADO_LIBRARY_TYPE=static build
> make[1]: Entering directory '/home/syner/Ada/ada-ado'
> libs=`echo '"no"' | sed -e 's,^ *,,' -e 's,  , ,g' -e 's, $,,g' | sed -e 's, ," \& ASCII.NUL \& ",g'` ; \
>     libs=`echo "$libs" | sed -e 's,ASCII.NUL & "" & ASCII.NUL,ASCII.NUL,g'`;\
> gnatprep -DMYSQL_LIB="$libs" src/mysql/mysql-lib.gpb src/mysql/mysql-lib.ads
> mysql=`(test Tno = Tyes && echo True) || echo False`; \
> sqlite=`(test Tyes = Tyes && echo True) || echo False`; \
> postgresql=`(test Tyes = Tyes && echo True) || echo False`; \
> gnatprep -DHAVE_MYSQL=$mysql \
>          -DHAVE_SQLITE=$sqlite \
>          -DHAVE_POSTGRESQL=$postgresql \
>          regtests/ado-testsuite-drivers.gpb regtests/ado-testsuite-drivers.adb
> mysql=`(test Tno = Tyes && echo True) || echo False`; \
> sqlite=`(test Tyes = Tyes && echo True) || echo False`; \
> postgresql=`(test Tyes = Tyes && echo True) || echo False`; \
> gnatprep -DHAVE_MYSQL=$mysql \
>           -DHAVE_SQLITE=$sqlite \
>           -DHAVE_POSTGRESQL=$postgresql \
>           src/static/ado-drivers-initialize.gpb src/static/ado-drivers-initialize.adb
> gprbuild -m -p -P"ado.gpr" -XMODE=distrib -XCOVERAGE=no -XADO_LIBRARY_TYPE=static -XPROCESSORS=8
> gnatgcc -c -g -O2 -gnat2012 -gnatafno -gnatVa -gnatwa ado-drivers-connections-postgresql.adb
> gnatgcc -c -g -O2 -gnat2012 -gnatafno -gnatVa -gnatwa ado-statements-postgresql.adb
> gnatgcc -c -g -O2 -gnat2012 -gnatafno -gnatVa -gnatwa pq.ads
> gnatgcc -c -g -O2 -gnat2012 -gnatafno -gnatVa -gnatwa ado-schemas-postgresql.adb
> gnatgcc -c -g -O2 -gnat2012 -gnatafno -gnatVa -gnatwa pq-perfect_hash.adb
> gnatgcc -c -g -O2 -gnat2012 -gnatafno -gnatVa -gnatwa ado-statements-sqlite.adb
> gnatgcc -c -g -O2 -gnat2012 -gnatafno -gnatVa -gnatwa sqlite3_h-perfect_hash.adb
> gnatgcc -c -g -O2 -gnat2012 -gnatafno -gnatVa -gnatwa ado-schemas-sqlite.adb
> gnatgcc -c -g -O2 -gnat2012 -gnatafno -gnatVa -gnatwa ado-drivers-connections-sqlite.adb
> gnatgcc -c -g -O2 -gnat2012 -gnatafno -gnatVa -gnatwa sqlite3_h.ads
> gnatgcc -c -g -O2 -gnat2012 -gnatafno -gnatVa -gnatwa ado-model.adb
> gnatgcc -c -g -O2 -gnat2012 -gnatafno -gnatVa -gnatwa ado-datasets.adb
> ado-statements-postgresql.adb:21:09: warning: unit "Ada.Unchecked_Conversion" is not referenced
> gnatgcc -c -g -O2 -gnat2012 -gnatafno -gnatVa -gnatwa ado.adb
> gnatgcc -c -g -O2 -gnat2012 -gnatafno -gnatVa -gnatwa ado-schemas.adb
> gnatgcc -c -g -O2 -gnat2012 -gnatafno -gnatVa -gnatwa ado-sessions.adb
> gnatgcc -c -g -O2 -gnat2012 -gnatafno -gnatVa -gnatwa ado-configs.adb
> gnatgcc -c -g -O2 -gnat2012 -gnatafno -gnatVa -gnatwa ado-schemas-databases.adb
> gnatgcc -c -g -O2 -gnat2012 -gnatafno -gnatVa -gnatwa ado-parameters.adb
> gnatgcc -c -g -O2 -gnat2012 -gnatafno -gnatVa -gnatwa ado-objects-cache.adb
> gnatgcc -c -g -O2 -gnat2012 -gnatafno -gnatVa -gnatwa ado-queries-loaders.adb
> gnatgcc -c -g -O2 -gnat2012 -gnatafno -gnatVa -gnatwa ado-objects.adb
> ado-queries-loaders.adb:27:06: file "util-serialize-io-xml.ads" not found
> 
>    compilation of ado-queries-loaders.adb failed
> 
> gprbuild: *** compilation phase failed
> Makefile:102: recipe for target 'build' failed
> make[1]: *** [build] Error 4
> make[1]: Leaving directory '/home/syner/Ada/ada-ado'
> Makefile:115: recipe for target 'static' failed
> make: *** [static] Error 2

**Comment by stcarrez** [comment]
Hi!

Thanks for the report.

That's because the Ada Util does not have the XML support.

You should install XmlAda (libxmlada5-dev package or similar) and then configure and build Ada Util again.

This will activate the XML support in Ada Util.
I'll improve the configure and documentation to check for that.
